//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baitaplon
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int Id { get; set; }
        public string TenSanPham { get; set; }
        public int NhaCungCapId { get; set; }
        public decimal Gia { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
